/* 
 * Radarr
 *
 * Radarr API docs
 *
 * OpenAPI spec version: 3.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
namespace Managarr.Server.APIs.Resources
{
    /// <summary>
    /// Defines DownloadProtocol
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum DownloadProtocol
    {
        /// <summary>
        /// Enum Unknown for value: unknown
        /// </summary>
        [EnumMember(Value = "unknown")]
        Unknown = 1,
        /// <summary>
        /// Enum Usenet for value: usenet
        /// </summary>
        [EnumMember(Value = "usenet")]
        Usenet = 2,
        /// <summary>
        /// Enum Torrent for value: torrent
        /// </summary>
        [EnumMember(Value = "torrent")]
        Torrent = 3
    }
}
